// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files.sql

package repository

import (
	"context"
	"database/sql"
)

const addFile = `-- name: AddFile :exec
INSERT INTO files (disk_path, virtual_path, mime_type, checksum, workspace_id)
VALUES (?, ?, ?, ?, ?)
`

type AddFileParams struct {
	DiskPath    string         `json:"disk_path"`
	VirtualPath string         `json:"virtual_path"`
	MimeType    sql.NullString `json:"mime_type"`
	Checksum    sql.NullString `json:"checksum"`
	WorkspaceID sql.NullInt64  `json:"workspace_id"`
}

func (q *Queries) AddFile(ctx context.Context, arg AddFileParams) error {
	_, err := q.db.ExecContext(ctx, addFile,
		arg.DiskPath,
		arg.VirtualPath,
		arg.MimeType,
		arg.Checksum,
		arg.WorkspaceID,
	)
	return err
}
