// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type File struct {
	ID          int64          `json:"id"`
	DiskPath    string         `json:"disk_path"`
	VirtualPath string         `json:"virtual_path"`
	MimeType    sql.NullString `json:"mime_type"`
	Checksum    sql.NullString `json:"checksum"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	WorkspaceID sql.NullInt64  `json:"workspace_id"`
}

type Workspace struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
