// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package repository

import (
	"context"
)

const addWorkspace = `-- name: AddWorkspace :exec
INSERT INTO workspaces (name, password)
VALUES (?, ?)
`

type AddWorkspaceParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) AddWorkspace(ctx context.Context, arg AddWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspace, arg.Name, arg.Password)
	return err
}
